---
- name: master
  hosts: master
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - master
    - backup-mysql

- name: slave-bind
  hosts: slave-bind
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - slave-bind
    - backup-mysql-slave

- name: slave-knotdns
  hosts: slave-knotdns
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - slave-knotdns
    - backup-mysql-slave

- name: slave-nsd
  hosts: slave-nsd
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - slave-nsd
    - backup-mysql-slave
